print(f"py_07")
print("first commit from master")
print("second commit from master")
print("first commit from branch")
print("second commit from branch")
print("third commit from master")
print("first commit from creature2")
print("second commit from creature2")
